# Generated by Django 4.0.4 on 2022-06-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postRecepies', '0004_remove_profile_location_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
