# Generated by Django 4.0.4 on 2022-06-06 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postRecepies', '0006_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='title',
            field=models.CharField(default='Hola', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL),
        ),
    ]
